services:
  front:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: tispa-front
    command: 'npm run dev'
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000

  db:
    image: postgres:14.1-alpine
    container_name: tispa-db
    environment:
      POSTGRES_DB: tispa_local
      POSTGRES_USER: tispa
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
